database:
  url: jdbc:mysql://localhost:3306/popsdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  username: pops
  password: p0ps#?025!

firebase:
  key-path: /opt/pops/keys/pops-srv-employee-firebase-adminsdk-fbsvc-e86c8fbf1b.json

odoo:
  url: https://grupo-pops1.odoo.com/jsonrpc
  db: grupo-pops1
  uid: 2
  password: agustd10

services:
  pops-srv-employee:
    url: http://localhost:8081/api-employee
  pops-srv-projects:
    url: http://localhost:8082/api-project
  squad-api:
    url: http://localhost:8083/api-squad
